"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ["main.py"]
DATA_FILES = []
OPTIONS = {
    "excludes": ["rubicon", "black", "pyright", "pillow", "Image"],
    "packages": ["pynput"],
    "includes": ["pandas", "numpy", "pyautogui", "pyinput", "cmath", "pyobjc-core", "pyobjc"],
    "resources": ["/Users/sanicket/Documents/GitHub/haystack-clean-display/.conda/lib"],
}  # , 'resources': ['.conda']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
